version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "127.0.0.1:27017:27017"
  core:
    image: binsky/thunder-server:latest
    environment:
      APP_VERBOSE: 3
      APP_SERVER.ADDRESS: "0.0.0.0"
      APP_DATABASE.URL: "mongodb://root:example@mongo:27017"
    links:
      - mongo
    ports:
      - "127.0.0.1:8080:8080"
