verbose = 3
debug = true
enable_public_registration = true
allowed_cors_origins = [
    "localhost", # allows requests from a local webserver
    "null"  # allows local requests without webserver
]

[server]
port = "8000"
address = "localhost"
url = "http://localhost:8000"

[database]
url = "mongodb://root:example@localhost:27017"
name = "thunder"
