verbose = 0
debug = false
enable_public_registration = false

[server]
port = "8080"
address = "localhost"
url = "http://localhost:8080"

[database]
url = "mongodb://localhost:27017"
name = "thunder"
